### ISSUE TITLE
Fails for ember-source@3.13.0

### ISSUE THREAD

**Issue by jelhan** [miguelcobain/ember-yeti-table#81]
It does not work for `ember-source@3.13.0`. It throws following error in tests:

```
not ok 94 Chrome 77.0 - [79 ms] - Integration | Component | yeti-table (sorting): using sort and clicking header afterwards works
    ---
        actual: >
            [object Object]
        stack: >
            TypeError: Cannot set property data of [object Object] which has only a getter
                at setWithMandatorySetter (http://localhost:7357/assets/vendor.js:32281:24)
                at set (http://localhost:7357/assets/vendor.js:16332:45)
                at http://localhost:7357/assets/vendor.js:17569:9
                at changeProperties (http://localhost:7357/assets/vendor.js:15867:7)
                at setProperties (http://localhost:7357/assets/vendor.js:17563:5)
                at Object.setProperties (http://localhost:7357/assets/vendor.js:28896:39)
                at CurlyComponentManager.update (http://localhost:7357/assets/vendor.js:7610:19)
                at UpdateComponentOpcode.evaluate (http://localhost:7357/assets/vendor.js:49533:15)
                at UpdatingVM.execute (http://localhost:7357/assets/vendor.js:51719:16)
                at RenderResult.rerender (http://localhost:7357/assets/vendor.js:52016:10)
        message: >
            Cannot set property data of [object Object] which has only a getter
        negative: >
            false
        browser log: |
```

This happens for nearly all tests. I see the same error on dummy apps index page.

To reproduce run `ember try:one ember-release` or update `ember-source` manually to `~3.13.0` in `package.json` and run `yarn install` afterwards.

**Comment by jelhan** [comment]
It throwing when it sets `data` argument of `<YetiTable>` the second time. This is using `argument` decorator provided by `@ember-decorators/argument`: https://github.com/miguelcobain/ember-yeti-table/blob/75722fe4d1371c0ac58565902a3f58f45f248b7a/addon/components/yeti-table/component.js#L124-L129

The tests for `@ember-decorators/argument` are also failing for `ember-source@3.13.0` with the same error message. If I got #75 and #51 right, this dependency is also blocking the upgrade to `ember-decorators@^6.0.0`. It might be the time to drop that dependency...

**Comment by miguelcobain** [comment]
Can you try depending on `miguelcobain/ember-yeti-table#master` to see if it fixes the problem?

Make sure to check the [CHANGELOG](https://github.com/miguelcobain/ember-yeti-table/blob/master/CHANGELOG.md) to know of all the breaking changes and exactly what happened.

This will be the `v1.0.0` soon.

**Comment by jelhan** [comment]
I can confirm that it's working fine now with `ember-source@3.13.2`. It also unblocks upgrade of other addons that require `ember-decorators@v6`. Thanks a lot!
